site_name: Unified Shield
site_description: Kernel Threat Detection and eBPF-LSM IPS Control Plane
site_author: hxuu

repo_name: hxuu/unified_shield
repo_url: https://github.com/hxuu/unified_shield

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    - toc:
          permalink: true

nav:
  - Home: index.md
  - API Reference: api-reference.md
  - Current Detectors: current-detectors.md
  - Extensibility Guide: extensibility.md
  - Detectors Format: detectors.md
  - Architecture: architecture.md
  - Extension Plan: extension-plan.md
  - Signature AV LSM: signature-av-lsm.md

